volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: bobgoze/foodgram_backend
    env_file:
    - .env
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    image: bobgoze/foodgram_frontend
    env_file:
      - .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: bobgoze/foodgram_gateway
    env_file:
      - .env
    ports:
      - 7000:80
    volumes:
      - static:/static
      - media:/media