# Generated by Django 5.2.3 on 2025-07-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ('-created_at',), 'verbose_name': 'Токен', 'verbose_name_plural': 'Токены'},
        ),
        migrations.AlterField(
            model_name='token',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Наличие короткой ссылки.'),
        ),
    ]
