# Generated by Django 5.2.3 on 2025-06-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.URLField(blank=True, help_text='Короткая ссылка на рецепт', null=True, verbose_name='Короткая ссылка на рецепт'),
        ),
    ]
