# Generated by Django 5.2.3 on 2025-07-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_alter_token_options_alter_token_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Слэг тэга', unique=True, verbose_name='Слаг'),
        ),
    ]
